export const NAV_LIST = [
  // {
  //   name: 'Home',
  //   status: true,
  //   value: 0,
  //   url: '/',
  //   hash: '',
  // },
  // {
  //   name: 'About',
  //   status: false,
  //   value: 1,
  //   url: '/about',
  //   hash: '',
  // },
  {
    name: 'Product',
    status: true,
    value: 0,
    url: '/product',
    hash: '',
  },
  {
    name: 'Product Rule',
    status: false,
    value: 1,
    url: '/product/rule',
    hash: '',
  },
  {
    name: 'Product Category',
    status: false,
    value: 2,
    url: '/product/category',
    hash: '',
  },
  {
    name: 'User',
    status: false,
    value: 3,
    url: '/user',
    hash: '',
  },
  {
    name: 'UserPage',
    status: false,
    value: 4,
    url: '/user#/singePage',
    hash: '',
  },
  {
    name: 'Order',
    status: false,
    value: 4,
    url: '/order',
    hash: '',
  },
]
